### ISSUE TITLE
Should the tool compute and print the size of each value associated with the listed keys?

### ISSUE THREAD

**Issue by Arteneko** [Arteneko/sinx#2]
Should the tool compute and print the size of each value associated with the listed keys?

In which case, the resulting format would be the following.

```
total <count>
<size 1> <key 1>
<size 2> <key 2>
<...> <...>
```

`size` is printed in bytes, and a `-H` flag should be added to print it in a human-friendly format.

**Comment by M0NsTeRRR** [comment]
I think the best is to use an argument like `-s` to get size.

**Comment by Arteneko** [comment]
Fine by me.

I updated the spec. at #1
